add: 게시판 폼 작성 디자인 1차
ash9river/SejongReuseHub pull request #13
Opened 2024-05-11 12:49 UTC by AhnRian

2024-05-12 09:07 UTC, ash9river requested changes
수정사항 반영해주시고 다시 merge해주세요

2024-05-12 09:07 UTC, ash9river commented on src/App.tsx
> +      {
이거 form인데 따로 페이지로 관리할 필요는 없는거같아요.
컴포넌트로 관리하죠,

2024-05-12 09:07 UTC, ash9river commented on src/index.tsx
> -
담부터는 불필요한 커밋은 안하는게 좋아보여요.

2024-05-12 09:07 UTC, ash9river commented on src/pages/PostPage.tsx
> +  const [formData, setFormData] = useState<FormData>({
formdata를 굳이 useState로 바인딩하지말고, FormData로 제출해주세요.

```
function handleSubmit(e: FormEvent<HTMLFormElement>){
    e.preventDefault();
    
    const fd=new FormData(event.target);
    const categoryData=fd.getAll("category");
    const data=Object.fromEntries(fd.entries());
    data.category=categoryData;
   // 등등...
}
```
이런식으로도 관리할 수 있어요.

2024-05-12 09:07 UTC, ash9river commented on src/services/mocks/handlers.ts
> -
이거 msw로 http요청 모킹할려고 한건데 지운 이유가 따로 있는건가요?

2024-05-12 13:41 UTC, AhnRian commented on src/App.tsx
> +      {
게시글 작성 페이지로 만든건데 그냥 맵에만 띄우는걸로 할건가요??

2024-05-12 13:50 UTC, AhnRian commented on src/services/mocks/handlers.ts
> -
제가 연습해보려고 임시로 넣은 코드 인줄 알았어요!

2024-05-12 14:02 UTC, AhnRian commented on src/pages/PostPage.tsx
> +  const [formData, setFormData] = useState<FormData>({
const [formData, setFormData] = useState<FormData>({
    title: '',
    content: '',
    author: '',
    password: '',
    category: 'general',
  });
  이 코드를 없애라고 하시는건가요??

2024-05-12 14:02 UTC, AhnRian commented on src/services/mocks/handlers.ts
> -
다시 추가하겠습니다

2024-05-13 06:24 UTC, ash9river commented on src/App.tsx
> +      {
어차피 모달로 띄워서 할건데 굳이 페이지로 할필요는없는거같아요

2024-05-13 06:24 UTC, ash9river commented on src/pages/PostPage.tsx
> +  const [formData, setFormData] = useState<FormData>({
아 넵 state로 바인딩하지 않아도 되거든요

2024-05-13 08:18 UTC, ash9river commented
확인했습니다

2024-05-13 08:18 UTC, merged